package appkit

type ImageFrameStyle uint

const (
	ImageFrameNone ImageFrameStyle = iota
	ImageFramePhoto
	ImageFrameGrayBezel
	ImageFrameGroove
	ImageFrameButton
)

type ImageAlignment uint

const (
	ImageAlignCenter ImageAlignment = iota
	ImageAlignTop
	ImageAlignTopLeft
	ImageAlignTopRight
	ImageAlignLeft
	ImageAlignBottom
	ImageAlignBottomLeft
	ImageAlignBottomRight
	ImageAlignRight
)

type ImageSymbolScale int

const (
	ImageSymbolScaleSmall  ImageSymbolScale = 1
	ImageSymbolScaleMedium ImageSymbolScale = 2
	ImageSymbolScaleLarge  ImageSymbolScale = 3
)

type ImageName string

var ImageNameAddTemplate = ImageName("NSAddTemplate")
var ImageNameBluetoothTemplate = ImageName("NSBluetoothTemplate")
var ImageNameBonjour = ImageName("NSBonjour")
var ImageNameBookmarksTemplate = ImageName("NSBookmarksTemplate")
var ImageNameCaution = ImageName("NSCaution")
var ImageNameComputer = ImageName("NSComputer")
var ImageNameEnterFullScreenTemplate = ImageName("NSEnterFullScreenTemplate")
var ImageNameExitFullScreenTemplate = ImageName("NSExitFullScreenTemplate")
var ImageNameFolder = ImageName("NSFolder")
var ImageNameFolderBurnable = ImageName("NSFolderBurnable")
var ImageNameFolderSmart = ImageName("NSFolderSmart")
var ImageNameFollowLinkFreestandingTemplate = ImageName("NSFollowLinkFreestandingTemplate")
var ImageNameHomeTemplate = ImageName("NSHomeTemplate")
var ImageNameIChatTheaterTemplate = ImageName("NSIChatTheaterTemplate")
var ImageNameLockLockedTemplate = ImageName("NSLockLockedTemplate")
var ImageNameLockUnlockedTemplate = ImageName("NSLockUnlockedTemplate")
var ImageNameNetwork = ImageName("NSNetwork")
var ImageNamePathTemplate = ImageName("NSPathTemplate")
var ImageNameQuickLookTemplate = ImageName("NSQuickLookTemplate")
var ImageNameRefreshFreestandingTemplate = ImageName("NSRefreshFreestandingTemplate")
var ImageNameRefreshTemplate = ImageName("NSRefreshTemplate")
var ImageNameRemoveTemplate = ImageName("NSRemoveTemplate")
var ImageNameRevealFreestandingTemplate = ImageName("NSRevealFreestandingTemplate")
var ImageNameShareTemplate = ImageName("NSShareTemplate")
var ImageNameSlideshowTemplate = ImageName("NSSlideshowTemplate")
var ImageNameStatusAvailable = ImageName("NSStatusAvailable")
var ImageNameStatusNone = ImageName("NSStatusNone")
var ImageNameStatusPartiallyAvailable = ImageName("NSStatusPartiallyAvailable")
var ImageNameStatusUnavailable = ImageName("NSStatusUnavailable")
var ImageNameStopProgressFreestandingTemplate = ImageName("NSStopProgressFreestandingTemplate")
var ImageNameStopProgressTemplate = ImageName("NSStopProgressTemplate")
var ImageNameTrashEmpty = ImageName("NSTrashEmpty")
var ImageNameTrashFull = ImageName("NSTrashFull")
var ImageNameActionTemplate = ImageName("NSActionTemplate")
var ImageNameSmartBadgeTemplate = ImageName("NSSmartBadgeTemplate")
var ImageNameIconViewTemplate = ImageName("NSIconViewTemplate")
var ImageNameListViewTemplate = ImageName("NSListViewTemplate")
var ImageNameColumnViewTemplate = ImageName("NSColumnViewTemplate")
var ImageNameFlowViewTemplate = ImageName("NSFlowViewTemplate")
var ImageNameInvalidDataFreestandingTemplate = ImageName("NSInvalidDataFreestandingTemplate")
var ImageNameGoForwardTemplate = ImageName("NSGoForwardTemplate")
var ImageNameGoBackTemplate = ImageName("NSGoBackTemplate")
var ImageNameGoRightTemplate = ImageName("NSGoRightTemplate")
var ImageNameGoLeftTemplate = ImageName("NSGoLeftTemplate")
var ImageNameRightFacingTriangleTemplate = ImageName("NSRightFacingTriangleTemplate")
var ImageNameLeftFacingTriangleTemplate = ImageName("NSLeftFacingTriangleTemplate")
var ImageNameMobileMe = ImageName("NSMobileMe")
var ImageNameMultipleDocuments = ImageName("NSMultipleDocuments")
var ImageNameUserAccounts = ImageName("NSUserAccounts")
var ImageNamePreferencesGeneral = ImageName("NSPreferencesGeneral")
var ImageNameAdvanced = ImageName("NSAdvanced")
var ImageNameInfo = ImageName("NSInfo")
var ImageNameFontPanel = ImageName("NSFontPanel")
var ImageNameColorPanel = ImageName("NSColorPanel")
var ImageNameUser = ImageName("NSUser")
var ImageNameUserGroup = ImageName("NSUserGroup")
var ImageNameEveryone = ImageName("NSEveryone")
var ImageNameUserGuest = ImageName("NSUserGuest")
var ImageNameMenuOnStateTemplate = ImageName("NSMenuOnStateTemplate")
var ImageNameMenuMixedStateTemplate = ImageName("NSMenuMixedStateTemplate")
var ImageNameApplicationIcon = ImageName("NSApplicationIcon")
var ImageNameTouchBarAddDetailTemplate = ImageName("NSTouchBarAddDetailTemplate")
var ImageNameTouchBarAddTemplate = ImageName("NSTouchBarAddTemplate")
var ImageNameTouchBarAlarmTemplate = ImageName("NSTouchBarAlarmTemplate")
var ImageNameTouchBarAudioInputMuteTemplate = ImageName("NSTouchBarAudioInputMuteTemplate")
var ImageNameTouchBarAudioInputTemplate = ImageName("NSTouchBarAudioInputTemplate")
var ImageNameTouchBarAudioOutputMuteTemplate = ImageName("NSTouchBarAudioOutputMuteTemplate")
var ImageNameTouchBarAudioOutputVolumeHighTemplate = ImageName("NSTouchBarAudioOutputVolumeHighTemplate")
var ImageNameTouchBarAudioOutputVolumeLowTemplate = ImageName("NSTouchBarAudioOutputVolumeLowTemplate")
var ImageNameTouchBarAudioOutputVolumeMediumTemplate = ImageName("NSTouchBarAudioOutputVolumeMediumTemplate")
var ImageNameTouchBarAudioOutputVolumeOffTemplate = ImageName("NSTouchBarAudioOutputVolumeOffTemplate")
var ImageNameTouchBarBookmarksTemplate = ImageName("NSTouchBarBookmarksTemplate")
var ImageNameTouchBarColorPickerFill = ImageName("NSTouchBarColorPickerFill")
var ImageNameTouchBarColorPickerFont = ImageName("NSTouchBarColorPickerFont")
var ImageNameTouchBarColorPickerStroke = ImageName("NSTouchBarColorPickerStroke")
var ImageNameTouchBarCommunicationAudioTemplate = ImageName("NSTouchBarCommunicationAudioTemplate")
var ImageNameTouchBarCommunicationVideoTemplate = ImageName("NSTouchBarCommunicationVideoTemplate")
var ImageNameTouchBarComposeTemplate = ImageName("NSTouchBarComposeTemplate")
var ImageNameTouchBarDeleteTemplate = ImageName("NSTouchBarDeleteTemplate")
var ImageNameTouchBarDownloadTemplate = ImageName("NSTouchBarDownloadTemplate")
var ImageNameTouchBarEnterFullScreenTemplate = ImageName("NSTouchBarEnterFullScreenTemplate")
var ImageNameTouchBarExitFullScreenTemplate = ImageName("NSTouchBarExitFullScreenTemplate")
var ImageNameTouchBarFastForwardTemplate = ImageName("NSTouchBarFastForwardTemplate")
var ImageNameTouchBarFolderCopyToTemplate = ImageName("NSTouchBarFolderCopyToTemplate")
var ImageNameTouchBarFolderMoveToTemplate = ImageName("NSTouchBarFolderMoveToTemplate")
var ImageNameTouchBarFolderTemplate = ImageName("NSTouchBarFolderTemplate")
var ImageNameTouchBarGetInfoTemplate = ImageName("NSTouchBarGetInfoTemplate")
var ImageNameTouchBarGoBackTemplate = ImageName("NSTouchBarGoBackTemplate")
var ImageNameTouchBarGoDownTemplate = ImageName("NSTouchBarGoDownTemplate")
var ImageNameTouchBarGoForwardTemplate = ImageName("NSTouchBarGoForwardTemplate")
var ImageNameTouchBarGoUpTemplate = ImageName("NSTouchBarGoUpTemplate")
var ImageNameTouchBarHistoryTemplate = ImageName("NSTouchBarHistoryTemplate")
var ImageNameTouchBarIconViewTemplate = ImageName("NSTouchBarIconViewTemplate")
var ImageNameTouchBarListViewTemplate = ImageName("NSTouchBarListViewTemplate")
var ImageNameTouchBarMailTemplate = ImageName("NSTouchBarMailTemplate")
var ImageNameTouchBarNewFolderTemplate = ImageName("NSTouchBarNewFolderTemplate")
var ImageNameTouchBarNewMessageTemplate = ImageName("NSTouchBarNewMessageTemplate")
var ImageNameTouchBarOpenInBrowserTemplate = ImageName("NSTouchBarOpenInBrowserTemplate")
var ImageNameTouchBarPauseTemplate = ImageName("NSTouchBarPauseTemplate")
var ImageNameTouchBarPlayPauseTemplate = ImageName("NSTouchBarPlayPauseTemplate")
var ImageNameTouchBarPlayTemplate = ImageName("NSTouchBarPlayTemplate")
var ImageNameTouchBarQuickLookTemplate = ImageName("NSTouchBarQuickLookTemplate")
var ImageNameTouchBarRecordStartTemplate = ImageName("NSTouchBarRecordStartTemplate")
var ImageNameTouchBarRecordStopTemplate = ImageName("NSTouchBarRecordStopTemplate")
var ImageNameTouchBarRefreshTemplate = ImageName("NSTouchBarRefreshTemplate")
var ImageNameTouchBarRemoveTemplate = ImageName("NSTouchBarRemoveTemplate")
var ImageNameTouchBarRewindTemplate = ImageName("NSTouchBarRewindTemplate")
var ImageNameTouchBarRotateLeftTemplate = ImageName("NSTouchBarRotateLeftTemplate")
var ImageNameTouchBarRotateRightTemplate = ImageName("NSTouchBarRotateRightTemplate")
var ImageNameTouchBarSearchTemplate = ImageName("NSTouchBarSearchTemplate")
var ImageNameTouchBarShareTemplate = ImageName("NSTouchBarShareTemplate")
var ImageNameTouchBarSidebarTemplate = ImageName("NSTouchBarSidebarTemplate")
var ImageNameTouchBarSkipAhead15SecondsTemplate = ImageName("NSTouchBarSkipAhead15SecondsTemplate")
var ImageNameTouchBarSkipAhead30SecondsTemplate = ImageName("NSTouchBarSkipAhead30SecondsTemplate")
var ImageNameTouchBarSkipAheadTemplate = ImageName("NSTouchBarSkipAheadTemplate")
var ImageNameTouchBarSkipBack15SecondsTemplate = ImageName("NSTouchBarSkipBack15SecondsTemplate")
var ImageNameTouchBarSkipBack30SecondsTemplate = ImageName("NSTouchBarSkipBack30SecondsTemplate")
var ImageNameTouchBarSkipBackTemplate = ImageName("NSTouchBarSkipBackTemplate")
var ImageNameTouchBarSkipToEndTemplate = ImageName("NSTouchBarSkipToEndTemplate")
var ImageNameTouchBarSkipToStartTemplate = ImageName("NSTouchBarSkipToStartTemplate")
var ImageNameTouchBarSlideshowTemplate = ImageName("NSTouchBarSlideshowTemplate")
var ImageNameTouchBarTagIconTemplate = ImageName("NSTouchBarTagIconTemplate")
var ImageNameTouchBarTextBoldTemplate = ImageName("NSTouchBarTextBoldTemplate")
var ImageNameTouchBarTextBoxTemplate = ImageName("NSTouchBarTextBoxTemplate")
var ImageNameTouchBarTextCenterAlignTemplate = ImageName("NSTouchBarTextCenterAlignTemplate")
var ImageNameTouchBarTextItalicTemplate = ImageName("NSTouchBarTextItalicTemplate")
var ImageNameTouchBarTextJustifiedAlignTemplate = ImageName("NSTouchBarTextJustifiedAlignTemplate")
var ImageNameTouchBarTextLeftAlignTemplate = ImageName("NSTouchBarTextLeftAlignTemplate")
var ImageNameTouchBarTextListTemplate = ImageName("NSTouchBarTextListTemplate")
var ImageNameTouchBarTextRightAlignTemplate = ImageName("NSTouchBarTextRightAlignTemplate")
var ImageNameTouchBarTextStrikethroughTemplate = ImageName("NSTouchBarTextStrikethroughTemplate")
var ImageNameTouchBarTextUnderlineTemplate = ImageName("NSTouchBarTextUnderlineTemplate")
var ImageNameTouchBarUserAddTemplate = ImageName("NSTouchBarUserAddTemplate")
var ImageNameTouchBarUserGroupTemplate = ImageName("NSTouchBarUserGroupTemplate")
var ImageNameTouchBarUserTemplate = ImageName("NSTouchBarUserTemplate")
var ImageNameTouchBarVolumeDownTemplate = ImageName("NSTouchBarVolumeDownTemplate")
var ImageNameTouchBarVolumeUpTemplate = ImageName("NSTouchBarVolumeUpTemplate")
var ImageNameTouchBarPlayheadTemplate = ImageName("NSTouchBarPlayheadTemplate")
