#import <stdbool.h>
#import <stdlib.h>
#import <utils.h>
#import <Appkit/Appkit.h>

void* C_ScrollView_Alloc();

void* C_NSScrollView_InitWithCoder(void* ptr, void* coder);
void* C_NSScrollView_InitWithFrame(void* ptr, CGRect frameRect);
void* C_NSScrollView_Init(void* ptr);
void C_NSScrollView_AddFloatingSubview_ForAxis(void* ptr, void* view, int axis);
void C_NSScrollView_Tile(void* ptr);
void C_NSScrollView_FlashScrollers(void* ptr);
void C_NSScrollView_MagnifyToFitRect(void* ptr, CGRect rect);
void C_NSScrollView_SetMagnification_CenteredAtPoint(void* ptr, double magnification, CGPoint point);
CGSize C_NSScrollView_ContentSize(void* ptr);
CGRect C_NSScrollView_DocumentVisibleRect(void* ptr);
void* C_NSScrollView_BackgroundColor(void* ptr);
void C_NSScrollView_SetBackgroundColor(void* ptr, void* value);
bool C_NSScrollView_DrawsBackground(void* ptr);
void C_NSScrollView_SetDrawsBackground(void* ptr, bool value);
unsigned int C_NSScrollView_BorderType(void* ptr);
void C_NSScrollView_SetBorderType(void* ptr, unsigned int value);
void* C_NSScrollView_DocumentCursor(void* ptr);
void C_NSScrollView_SetDocumentCursor(void* ptr, void* value);
void* C_NSScrollView_ContentView(void* ptr);
void C_NSScrollView_SetContentView(void* ptr, void* value);
void* C_NSScrollView_DocumentView(void* ptr);
void C_NSScrollView_SetDocumentView(void* ptr, void* value);
void* C_NSScrollView_HorizontalScroller(void* ptr);
void C_NSScrollView_SetHorizontalScroller(void* ptr, void* value);
bool C_NSScrollView_HasHorizontalScroller(void* ptr);
void C_NSScrollView_SetHasHorizontalScroller(void* ptr, bool value);
void* C_NSScrollView_VerticalScroller(void* ptr);
void C_NSScrollView_SetVerticalScroller(void* ptr, void* value);
bool C_NSScrollView_HasVerticalScroller(void* ptr);
void C_NSScrollView_SetHasVerticalScroller(void* ptr, bool value);
bool C_NSScrollView_AutohidesScrollers(void* ptr);
void C_NSScrollView_SetAutohidesScrollers(void* ptr, bool value);
bool C_NSScrollView_HasHorizontalRuler(void* ptr);
void C_NSScrollView_SetHasHorizontalRuler(void* ptr, bool value);
void* C_NSScrollView_HorizontalRulerView(void* ptr);
void C_NSScrollView_SetHorizontalRulerView(void* ptr, void* value);
bool C_NSScrollView_HasVerticalRuler(void* ptr);
void C_NSScrollView_SetHasVerticalRuler(void* ptr, bool value);
void* C_NSScrollView_VerticalRulerView(void* ptr);
void C_NSScrollView_SetVerticalRulerView(void* ptr, void* value);
bool C_NSScrollView_RulersVisible(void* ptr);
void C_NSScrollView_SetRulersVisible(void* ptr, bool value);
bool C_NSScrollView_AutomaticallyAdjustsContentInsets(void* ptr);
void C_NSScrollView_SetAutomaticallyAdjustsContentInsets(void* ptr, bool value);
NSEdgeInsets C_NSScrollView_ContentInsets(void* ptr);
void C_NSScrollView_SetContentInsets(void* ptr, NSEdgeInsets value);
NSEdgeInsets C_NSScrollView_ScrollerInsets(void* ptr);
void C_NSScrollView_SetScrollerInsets(void* ptr, NSEdgeInsets value);
int C_NSScrollView_ScrollerKnobStyle(void* ptr);
void C_NSScrollView_SetScrollerKnobStyle(void* ptr, int value);
int C_NSScrollView_ScrollerStyle(void* ptr);
void C_NSScrollView_SetScrollerStyle(void* ptr, int value);
double C_NSScrollView_LineScroll(void* ptr);
void C_NSScrollView_SetLineScroll(void* ptr, double value);
double C_NSScrollView_HorizontalLineScroll(void* ptr);
void C_NSScrollView_SetHorizontalLineScroll(void* ptr, double value);
double C_NSScrollView_VerticalLineScroll(void* ptr);
void C_NSScrollView_SetVerticalLineScroll(void* ptr, double value);
double C_NSScrollView_PageScroll(void* ptr);
void C_NSScrollView_SetPageScroll(void* ptr, double value);
double C_NSScrollView_HorizontalPageScroll(void* ptr);
void C_NSScrollView_SetHorizontalPageScroll(void* ptr, double value);
double C_NSScrollView_VerticalPageScroll(void* ptr);
void C_NSScrollView_SetVerticalPageScroll(void* ptr, double value);
bool C_NSScrollView_ScrollsDynamically(void* ptr);
void C_NSScrollView_SetScrollsDynamically(void* ptr, bool value);
int C_NSScrollView_FindBarPosition(void* ptr);
void C_NSScrollView_SetFindBarPosition(void* ptr, int value);
bool C_NSScrollView_UsesPredominantAxisScrolling(void* ptr);
void C_NSScrollView_SetUsesPredominantAxisScrolling(void* ptr, bool value);
int C_NSScrollView_HorizontalScrollElasticity(void* ptr);
void C_NSScrollView_SetHorizontalScrollElasticity(void* ptr, int value);
int C_NSScrollView_VerticalScrollElasticity(void* ptr);
void C_NSScrollView_SetVerticalScrollElasticity(void* ptr, int value);
bool C_NSScrollView_AllowsMagnification(void* ptr);
void C_NSScrollView_SetAllowsMagnification(void* ptr, bool value);
double C_NSScrollView_Magnification(void* ptr);
void C_NSScrollView_SetMagnification(void* ptr, double value);
double C_NSScrollView_MaxMagnification(void* ptr);
void C_NSScrollView_SetMaxMagnification(void* ptr, double value);
double C_NSScrollView_MinMagnification(void* ptr);
void C_NSScrollView_SetMinMagnification(void* ptr, double value);
