#import <stdbool.h>
#import <stdlib.h>
#import <utils.h>
#import <Foundation/NSGeometry.h>
#import <Foundation/NSRange.h>

void* C_TableView_Alloc();

void* C_NSTableView_InitWithCoder(void* ptr, void* coder);
void* C_NSTableView_InitWithFrame(void* ptr, CGRect frameRect);
void* C_NSTableView_Init(void* ptr);
void* C_NSTableView_AllocTableView();
void* C_NSTableView_NewTableView();
void* C_NSTableView_Autorelease(void* ptr);
void* C_NSTableView_Retain(void* ptr);
void C_NSTableView_ReloadData(void* ptr);
void C_NSTableView_ReloadDataForRowIndexes_ColumnIndexes(void* ptr, void* rowIndexes, void* columnIndexes);
void* C_NSTableView_MakeViewWithIdentifier_Owner(void* ptr, void* identifier, void* owner);
void* C_NSTableView_RowViewAtRow_MakeIfNecessary(void* ptr, int row, bool makeIfNecessary);
void* C_NSTableView_ViewAtColumn_Row_MakeIfNecessary(void* ptr, int column, int row, bool makeIfNecessary);
void C_NSTableView_BeginUpdates(void* ptr);
void C_NSTableView_EndUpdates(void* ptr);
void C_NSTableView_MoveRowAtIndex_ToIndex(void* ptr, int oldIndex, int newIndex);
void C_NSTableView_InsertRowsAtIndexes_WithAnimation(void* ptr, void* indexes, unsigned int animationOptions);
void C_NSTableView_RemoveRowsAtIndexes_WithAnimation(void* ptr, void* indexes, unsigned int animationOptions);
int C_NSTableView_RowForView(void* ptr, void* view);
int C_NSTableView_ColumnForView(void* ptr, void* view);
void C_NSTableView_RegisterNib_ForIdentifier(void* ptr, void* nib, void* identifier);
void* C_NSTableView_IndicatorImageInTableColumn(void* ptr, void* tableColumn);
void C_NSTableView_SetIndicatorImage_InTableColumn(void* ptr, void* image, void* tableColumn);
void C_NSTableView_AddTableColumn(void* ptr, void* tableColumn);
void C_NSTableView_RemoveTableColumn(void* ptr, void* tableColumn);
void C_NSTableView_MoveColumn_ToColumn(void* ptr, int oldIndex, int newIndex);
int C_NSTableView_ColumnWithIdentifier(void* ptr, void* identifier);
void* C_NSTableView_TableColumnWithIdentifier(void* ptr, void* identifier);
void C_NSTableView_SelectColumnIndexes_ByExtendingSelection(void* ptr, void* indexes, bool extend);
void C_NSTableView_DeselectColumn(void* ptr, int column);
bool C_NSTableView_IsColumnSelected(void* ptr, int column);
void C_NSTableView_SelectRowIndexes_ByExtendingSelection(void* ptr, void* indexes, bool extend);
void C_NSTableView_DeselectRow(void* ptr, int row);
bool C_NSTableView_IsRowSelected(void* ptr, int row);
void C_NSTableView_SelectAll(void* ptr, void* sender);
void C_NSTableView_DeselectAll(void* ptr, void* sender);
void C_NSTableView_EditColumn_Row_WithEvent_Select(void* ptr, int column, int row, void* event, bool _select);
void C_NSTableView_DidAddRowView_ForRow(void* ptr, void* rowView, int row);
void C_NSTableView_DidRemoveRowView_ForRow(void* ptr, void* rowView, int row);
CGRect C_NSTableView_RectOfColumn(void* ptr, int column);
CGRect C_NSTableView_RectOfRow(void* ptr, int row);
NSRange C_NSTableView_RowsInRect(void* ptr, CGRect rect);
void* C_NSTableView_ColumnIndexesInRect(void* ptr, CGRect rect);
int C_NSTableView_ColumnAtPoint(void* ptr, CGPoint point);
int C_NSTableView_RowAtPoint(void* ptr, CGPoint point);
CGRect C_NSTableView_FrameOfCellAtColumn_Row(void* ptr, int column, int row);
void C_NSTableView_SizeLastColumnToFit(void* ptr);
void C_NSTableView_NoteNumberOfRowsChanged(void* ptr);
void C_NSTableView_Tile(void* ptr);
void C_NSTableView_NoteHeightOfRowsWithIndexesChanged(void* ptr, void* indexSet);
void C_NSTableView_DrawRow_ClipRect(void* ptr, int row, CGRect clipRect);
void C_NSTableView_DrawGridInClipRect(void* ptr, CGRect clipRect);
void C_NSTableView_HighlightSelectionInClipRect(void* ptr, CGRect clipRect);
void C_NSTableView_DrawBackgroundInClipRect(void* ptr, CGRect clipRect);
void C_NSTableView_ScrollRowToVisible(void* ptr, int row);
void C_NSTableView_ScrollColumnToVisible(void* ptr, int column);
bool C_NSTableView_CanDragRowsWithIndexes_AtPoint(void* ptr, void* rowIndexes, CGPoint mouseDownPoint);
void C_NSTableView_SetDraggingSourceOperationMask_ForLocal(void* ptr, unsigned int mask, bool isLocal);
void C_NSTableView_SetDropRow_DropOperation(void* ptr, int row, unsigned int dropOperation);
void C_NSTableView_HideRowsAtIndexes_WithAnimation(void* ptr, void* indexes, unsigned int rowAnimation);
void C_NSTableView_UnhideRowsAtIndexes_WithAnimation(void* ptr, void* indexes, unsigned int rowAnimation);
void* C_NSTableView_DataSource(void* ptr);
void C_NSTableView_SetDataSource(void* ptr, void* value);
bool C_NSTableView_UsesStaticContents(void* ptr);
void C_NSTableView_SetUsesStaticContents(void* ptr, bool value);
Dictionary C_NSTableView_RegisteredNibsByIdentifier(void* ptr);
void* C_NSTableView_DoubleAction(void* ptr);
void C_NSTableView_SetDoubleAction(void* ptr, void* value);
int C_NSTableView_ClickedColumn(void* ptr);
int C_NSTableView_ClickedRow(void* ptr);
bool C_NSTableView_AllowsColumnReordering(void* ptr);
void C_NSTableView_SetAllowsColumnReordering(void* ptr, bool value);
bool C_NSTableView_AllowsColumnResizing(void* ptr);
void C_NSTableView_SetAllowsColumnResizing(void* ptr, bool value);
bool C_NSTableView_AllowsMultipleSelection(void* ptr);
void C_NSTableView_SetAllowsMultipleSelection(void* ptr, bool value);
bool C_NSTableView_AllowsEmptySelection(void* ptr);
void C_NSTableView_SetAllowsEmptySelection(void* ptr, bool value);
bool C_NSTableView_AllowsColumnSelection(void* ptr);
void C_NSTableView_SetAllowsColumnSelection(void* ptr, bool value);
bool C_NSTableView_UsesAutomaticRowHeights(void* ptr);
void C_NSTableView_SetUsesAutomaticRowHeights(void* ptr, bool value);
CGSize C_NSTableView_IntercellSpacing(void* ptr);
void C_NSTableView_SetIntercellSpacing(void* ptr, CGSize value);
double C_NSTableView_RowHeight(void* ptr);
void C_NSTableView_SetRowHeight(void* ptr, double value);
void* C_NSTableView_BackgroundColor(void* ptr);
void C_NSTableView_SetBackgroundColor(void* ptr, void* value);
bool C_NSTableView_UsesAlternatingRowBackgroundColors(void* ptr);
void C_NSTableView_SetUsesAlternatingRowBackgroundColors(void* ptr, bool value);
int C_NSTableView_Style(void* ptr);
void C_NSTableView_SetStyle(void* ptr, int value);
int C_NSTableView_EffectiveStyle(void* ptr);
int C_NSTableView_SelectionHighlightStyle(void* ptr);
void C_NSTableView_SetSelectionHighlightStyle(void* ptr, int value);
void* C_NSTableView_GridColor(void* ptr);
void C_NSTableView_SetGridColor(void* ptr, void* value);
unsigned int C_NSTableView_GridStyleMask(void* ptr);
void C_NSTableView_SetGridStyleMask(void* ptr, unsigned int value);
int C_NSTableView_EffectiveRowSizeStyle(void* ptr);
int C_NSTableView_RowSizeStyle(void* ptr);
void C_NSTableView_SetRowSizeStyle(void* ptr, int value);
Array C_NSTableView_TableColumns(void* ptr);
int C_NSTableView_SelectedColumn(void* ptr);
void* C_NSTableView_SelectedColumnIndexes(void* ptr);
int C_NSTableView_NumberOfSelectedColumns(void* ptr);
int C_NSTableView_SelectedRow(void* ptr);
void* C_NSTableView_SelectedRowIndexes(void* ptr);
int C_NSTableView_NumberOfSelectedRows(void* ptr);
bool C_NSTableView_AllowsTypeSelect(void* ptr);
void C_NSTableView_SetAllowsTypeSelect(void* ptr, bool value);
int C_NSTableView_NumberOfColumns(void* ptr);
int C_NSTableView_NumberOfRows(void* ptr);
bool C_NSTableView_FloatsGroupRows(void* ptr);
void C_NSTableView_SetFloatsGroupRows(void* ptr, bool value);
int C_NSTableView_EditedColumn(void* ptr);
int C_NSTableView_EditedRow(void* ptr);
void* C_NSTableView_HeaderView(void* ptr);
void C_NSTableView_SetHeaderView(void* ptr, void* value);
void* C_NSTableView_CornerView(void* ptr);
void C_NSTableView_SetCornerView(void* ptr, void* value);
unsigned int C_NSTableView_ColumnAutoresizingStyle(void* ptr);
void C_NSTableView_SetColumnAutoresizingStyle(void* ptr, unsigned int value);
bool C_NSTableView_AutosaveTableColumns(void* ptr);
void C_NSTableView_SetAutosaveTableColumns(void* ptr, bool value);
void* C_NSTableView_AutosaveName(void* ptr);
void C_NSTableView_SetAutosaveName(void* ptr, void* value);
void* C_NSTableView_Delegate(void* ptr);
void C_NSTableView_SetDelegate(void* ptr, void* value);
void* C_NSTableView_HighlightedTableColumn(void* ptr);
void C_NSTableView_SetHighlightedTableColumn(void* ptr, void* value);
bool C_NSTableView_VerticalMotionCanBeginDrag(void* ptr);
void C_NSTableView_SetVerticalMotionCanBeginDrag(void* ptr, bool value);
int C_NSTableView_DraggingDestinationFeedbackStyle(void* ptr);
void C_NSTableView_SetDraggingDestinationFeedbackStyle(void* ptr, int value);
Array C_NSTableView_SortDescriptors(void* ptr);
void C_NSTableView_SetSortDescriptors(void* ptr, Array value);
bool C_NSTableView_RowActionsVisible(void* ptr);
void C_NSTableView_SetRowActionsVisible(void* ptr, bool value);
void* C_NSTableView_HiddenRowIndexes(void* ptr);
